[package]
name = "add-correlation-id"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.99"
spin-sdk = "4.0.0"
uuid = { version = "1.18.0", features = ["v4"] }
wasi = "0.13.1+wasi-0.2.0"
